// This file is part of cordial. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/cordial/master/COPYRIGHT. No part of predicator, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2017 The developers of cordial. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/cordial/master/COPYRIGHT.


use super::*;
use super::hjson::*;
use super::webserver::RsaManyServersResolvesServerCert;
use super::webserver::UpdatableTlsServerConfigurationFactory;
use super::webserver::Webserver;
use super::webserver::requestHandlers::*;
use super::webserver::requestHandlerFactories::*;
use ::base64::encode_config as base64Encode;
use ::base64::URL_SAFE_NO_PAD;
use ::handlebars::Handlebars;
use ::hyper::StatusCode;
use ::hyper::header::ContentType;
use ::hyper::mime::Mime;
use ::hyper::mime::TEXT_CSS;
use ::mktemp::Temp;
use ::net2::TcpBuilder;
use ::net2::TcpListenerExt;
use ::net2::unix::UnixTcpBuilderExt;
use ::ordermap::OrderMap;
use ::rustls::ServerConfig;
use ::rustls::ServerSessionMemoryCache;
use ::serde_hjson::Map as HjsonMap;
use ::serde_hjson::Value as HjsonValue;
use ::std::collections::HashMap;
use ::std::collections::HashSet;
use ::std::io::Write;
use ::std::mem::transmute;
use ::std::net::*;
use ::std::os::unix::fs::FileTypeExt;
use ::std::path::Path;
use ::std::path::PathBuf;
use ::std::path::Component::Normal;
use ::std::str::FromStr;
use ::std::sync::Arc;
use ::std::time::Duration;
use ::std::time::SystemTime;
use ::std::time::UNIX_EPOCH;
use ::tokio_core::reactor::Handle;
use ::url::Url;

include!("Abstract.rs");
include!("brotli.rs");
include!("BrotliCompressionMode.rs");
include!("compression.rs");
include!("Configuration.rs");
include!("DiscoverResources.rs");
include!("gzip.rs");
include!("ImageTransformation.rs");
include!("InputImageFormat.rs");
include!("language.rs");
include!("localization.rs");
include!("pipeline.rs");
include!("resource.rs");
include!("ResourceTemplates.rs");
include!("ServerSocket.rs");
include!("Settings.rs");
include!("Variant.rs");
