// This file is part of cordial. It is subject to the license terms in the COPYRIGHT file found in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/cordial/master/COPYRIGHT. No part of predicator, including this file, may be copied, modified, propagated, or distributed except according to the terms contained in the COPYRIGHT file.
// Copyright © 2017 The developers of cordial. See the COPYRIGHT file in the top-level directory of this distribution and at https://raw.githubusercontent.com/lemonrock/cordial/master/COPYRIGHT.


/// Names are the preferred English spelling
/// The list is derived from <https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes>
/// Where a language is known by more than one name, the first in the list at Wikipedia is used.
/// Where a language name contains a character unrepresentable in code, an underscore is used.
/// It is believed that `Church Slavic` has a hidden hard space on wikipedia and this has been corrected.
//noinspection SpellCheckingInspection,NonAsciiCharacters
#[derive(Debug, Copy, Clone, Ord, PartialOrd, Eq, PartialEq, Hash)]
pub(crate) enum Iso639Language
{
	Abkhazian,
	Afar,
	Afrikaans,
	Akan,
	Albanian,
	Amharic,
	Arabic,
	Aragonese,
	Armenian,
	Assamese,
	Avaric,
	Avestan,
	Aymara,
	Azerbaijani,
	Bambara,
	Bashkir,
	Basque,
	Belarusian,
	Bengali,
	Bihari,
	Bislama,
	Bosnian,
	Breton,
	Bulgarian,
	Burmese,
	Catalan,
	Central_Khmer,
	Chamorro,
	Chechen,
	Chichewa,
	Chinese,
	Church_Slavic,
	Chuvash,
	Cornish,
	Corsican,
	Cree,
	Croatian,
	Czech,
	Danish,
	Divehi,
	Dutch,
	Dzongkha,
	English,
	Esperanto,
	Estonian,
	Ewe,
	Faroese,
	Fijian,
	Finnish,
	French,
	Fulah,
	Gaelic,
	Galician,
	Ganda,
	Georgian,
	German,
	Greek,
	Guarani,
	Gujarati,
	Haitian,
	Hausa,
	Hebrew,
	Herero,
	Hindi,
	Hiri_Motu,
	Hungarian,
	Icelandic,
	Ido,
	Igbo,
	Indonesian,
	Interlingua,
	Interlingue,
	Inuktitut,
	Inupiaq,
	Irish,
	Italian,
	Japanese,
	Javanese,
	Kalaallisut,
	Kannada,
	Kanuri,
	Kashmiri,
	Kazakh,
	Kikuyu,
	Kinyarwanda,
	Kirghiz,
	Komi,
	Kongo,
	Korean,
	Kuanyama,
	Kurdish,
	Lao,
	Latin,
	Latvian,
	Limburgan,
	Lingala,
	Lithuanian,
	Luba_Katanga,
	Luxembourgish,
	Macedonian,
	Malagasy,
	Malay,
	Malayalam,
	Maltese,
	Manx,
	Maori,
	Marathi,
	Marshallese,
	Mongolian,
	Nauru,
	Navajo,
	Ndonga,
	Nepali,
	North_Ndebele,
	Northern_Sami,
	Norwegian,
	Norwegian_Bokmal,
	Norwegian_Nynorsk,
	Occitan,
	Ojibwa,
	Oriya,
	Oromo,
	Ossetian,
	Pali,
	Panjabi,
	Pashto,
	Persian,
	Polish,
	Portuguese,
	Quechua,
	Romanian,
	Romansh,
	Rundi,
	Russian,
	Samoan,
	Sango,
	Sanskrit,
	Sardinian,
	Serbian,
	Shona,
	Sichuan_Yi,
	Sindhi,
	Sinhala,
	Slovak,
	Slovenian,
	Somali,
	South_Ndebele,
	Southern_Sotho,
	Spanish,
	Sundanese,
	Swahili,
	Swati,
	Swedish,
	Tagalog,
	Tahitian,
	Tajik,
	Tamil,
	Tatar,
	Telugu,
	Thai,
	Tibetan,
	Tigrinya,
	Tonga,
	Tsonga,
	Tswana,
	Turkish,
	Turkmen,
	Twi,
	Uighur,
	Ukrainian,
	Urdu,
	Uzbek,
	Venda,
	Vietnamese,
	Volapuk,
	Walloon,
	Welsh,
	Western_Frisian,
	Wolof,
	Xhosa,
	Yiddish,
	Yoruba,
	Zhuang,
	Zulu,
}

impl Default for Iso639Language
{
	#[inline(always)]
	fn default() -> Self
	{
		Iso639Language::English
	}
}

impl Display for Iso639Language
{
	fn fmt(&self, f: &mut Formatter) -> fmt::Result
	{
		write!(f, "{}", self.wikipedia_preferred_english_spelling())
	}
}

impl<'de> Deserialize<'de> for Iso639Language
{
	#[inline(always)]
	fn deserialize<D: Deserializer<'de>>(deserializer: D) -> Result<Self, D::Error>
	{
		struct Iso639LanguageVisitor;
		
		impl<'de> Visitor<'de> for Iso639LanguageVisitor
		{
			type Value = Iso639Language;
			
			#[inline(always)]
			fn expecting(&self, formatter: &mut Formatter) -> fmt::Result
			{
				formatter.write_str("an ISO 639-1 language code or the English spelling of a language")
			}
			
			#[inline(always)]
			fn visit_string<E: DeserializeError>(self, v: String) -> Result<Self::Value, E>
			{
				self.visit_str(&v)
			}
			
			#[inline(always)]
			fn visit_borrowed_str<E: DeserializeError>(self, v: &'de str) -> Result<Self::Value, E>
			{
				self.visit_str(&v)
			}
			
			#[inline(always)]
			fn visit_str<E: DeserializeError>(self, v: &str) -> Result<Self::Value, E>
			{
				match Iso639Language::from_english_spelling(v)
				{
					Some(value) => Ok(value),
					None => match Iso639Language::from_lower_case_iso_639_1_alpha_2_language_code(v)
					{
						Some(value) => Ok(value),
						None => match Iso639Language::from_lower_case_iso_639_1_alpha_2_language_code(&v.to_ascii_lowercase())
						{
							Some(value) => Ok(value),
							None => Err(E::custom("could not match value to an ISO 639-1 language code or the English spelling of a language"))
						}
					}
				}
			}
		}
		
		deserializer.deserialize_str(Iso639LanguageVisitor)
	}
}

impl Serialize for Iso639Language
{
	#[inline(always)]
	fn serialize<S: Serializer>(&self, serializer: S) -> Result<S::Ok, S::Error>
	{
		serializer.serialize_str(self.to_iso_639_1_alpha_2_language_code())
	}
}

impl Iso639Language
{
	#[inline(always)]
	pub(crate) fn from_english_spelling(name: &str) -> Option<Self>
	{
		use self::Iso639Language::*;
		
		match name
		{
			"Abkhazian" | "Abkhaz" => Some(Abkhazian),
			"Afar" => Some(Afar),
			"Afrikaans" => Some(Afrikaans),
			"Akan" | "Fanti" => Some(Akan),
			"Albanian" => Some(Albanian),
			"Amharic" => Some(Amharic),
			"Arabic" => Some(Arabic),
			"Aragonese" => Some(Aragonese),
			"Armenian" => Some(Armenian),
			"Assamese" => Some(Assamese),
			"Avaric" | "Avar" => Some(Avaric),
			"Avestan" => Some(Avestan),
			"Aymara" => Some(Aymara),
			"Azerbaijani" => Some(Azerbaijani),
			"Bambara" => Some(Bambara),
			"Bashkir" => Some(Bashkir),
			"Basque" => Some(Basque),
			"Belarusian" => Some(Belarusian),
			"Bengali" | "Bangla" => Some(Bengali),
			"Bihari" | "Bhojpuri" | "Magahi" | "Maithili" => Some(Bihari),
			"Bislama" => Some(Bislama),
			"Bosnian" => Some(Bosnian),
			"Breton" => Some(Breton),
			"Bulgarian" => Some(Bulgarian),
			"Burmese" => Some(Burmese),
			"Catalan" | "Valencian" => Some(Catalan),
			"Central Khmer" | "Khmer" | "Cambodian" => Some(Central_Khmer),
			"Chamorro" => Some(Chamorro),
			"Chechen" => Some(Chechen),
			"Chichewa" | "Chewa" | "Nyanja" => Some(Chichewa),
			"Chinese" => Some(Chinese),
			"Church Slavic" | "Church Slavonic" | "Old Church Slavonic" | "Old Slavonic" | "Old Bulgarian" => Some(Church_Slavic),
			"Chuvash" => Some(Chuvash),
			"Cornish" => Some(Cornish),
			"Corsican" => Some(Corsican),
			"Cree" => Some(Cree),
			"Croatian" => Some(Croatian),
			"Czech" => Some(Czech),
			"Danish" => Some(Danish),
			"Divehi" | "Dhivehi" | "Maldivian" => Some(Divehi),
			"Dutch" => Some(Dutch),
			"Dzongkha" => Some(Dzongkha),
			"English" => Some(English),
			"Esperanto" => Some(Esperanto),
			"Estonian" => Some(Estonian),
			"Ewe" => Some(Ewe),
			"Faroese" => Some(Faroese),
			"Fijian" => Some(Fijian),
			"Finnish" => Some(Finnish),
			"French" => Some(French),
			"Fulah" | "Fula" => Some(Fulah),
			"Gaelic" | "Scottish Gaelic" => Some(Gaelic),
			"Galician" => Some(Galician),
			"Ganda" => Some(Ganda),
			"Georgian" => Some(Georgian),
			"German" => Some(German),
			"Greek" => Some(Greek),
			"Guaraní" | "Guarani" => Some(Guarani),
			"Gujarati" => Some(Gujarati),
			"Haitian" | "Haitian Creole" => Some(Haitian),
			"Hausa" => Some(Hausa),
			"Hebrew" => Some(Hebrew),
			"Herero" => Some(Herero),
			"Hindi" => Some(Hindi),
			"Hiri Motu" => Some(Hiri_Motu),
			"Hungarian" => Some(Hungarian),
			"Icelandic" => Some(Icelandic),
			"Ido" => Some(Ido),
			"Igbo" => Some(Igbo),
			"Indonesian" => Some(Indonesian),
			"Interlingua" => Some(Interlingua),
			"Interlingue" => Some(Interlingue),
			"Inuktitut" => Some(Inuktitut),
			"Inupiaq" => Some(Inupiaq),
			"Irish" => Some(Irish),
			"Italian" => Some(Italian),
			"Japanese" => Some(Japanese),
			"Javanese" => Some(Javanese),
			"Kalaallisut" | "Greenlandic" => Some(Kalaallisut),
			"Kannada" => Some(Kannada),
			"Kanuri" => Some(Kanuri),
			"Kashmiri" => Some(Kashmiri),
			"Kazakh" => Some(Kazakh),
			"Kikuyu" | "Gikuyu" => Some(Kikuyu),
			"Kinyarwanda" => Some(Kinyarwanda),
			"Kirghiz" | "Kyrgyz" => Some(Kirghiz),
			"Komi" => Some(Komi),
			"Kongo" => Some(Kongo),
			"Korean" => Some(Korean),
			"Kuanyama" | "Kwanyama" => Some(Kuanyama),
			"Kurdish" => Some(Kurdish),
			"Lao" => Some(Lao),
			"Latin" => Some(Latin),
			"Latvian" => Some(Latvian),
			"Limburgan" | "Limburger" | "Limburgish" => Some(Limburgan),
			"Lingala" => Some(Lingala),
			"Lithuanian" => Some(Lithuanian),
			"Luba-Katanga" | "Luba-Shaba" => Some(Luba_Katanga),
			"Luxembourgish" | "Letzeburgesch" => Some(Luxembourgish),
			"Macedonian" => Some(Macedonian),
			"Malagasy" => Some(Malagasy),
			"Malay" => Some(Malay),
			"Malayalam" => Some(Malayalam),
			"Maltese" => Some(Maltese),
			"Manx" => Some(Manx),
			"Maori" | "Māori" => Some(Maori),
			"Marathi" | "Marāṭhī" => Some(Marathi),
			"Marshallese" => Some(Marshallese),
			"Mongolian" => Some(Mongolian),
			"Nauru" => Some(Nauru),
			"Navajo" | "Navaho" => Some(Navajo),
			"Ndonga" => Some(Ndonga),
			"Nepali" => Some(Nepali),
			"North Ndebele" | "Northern Ndebele" => Some(North_Ndebele),
			"Northern Sami" => Some(Northern_Sami),
			"Norwegian" => Some(Norwegian),
			"Norwegian Bokmål" | "Norwegian Bokmal" => Some(Norwegian_Bokmal),
			"Norwegian Nynorsk" => Some(Norwegian_Nynorsk),
			"Occitan" => Some(Occitan),
			"Ojibwa" | "Ojibwe" => Some(Ojibwa),
			"Oriya" | "Odia" => Some(Oriya),
			"Oromo" => Some(Oromo),
			"Ossetian" | "Ossetic" => Some(Ossetian),
			"Pali" | "Pāli" => Some(Pali),
			"Panjabi" | "Punjabi" => Some(Panjabi),
			"Pashto" | "Pushto" => Some(Pashto),
			"Persian" | "Farsi" => Some(Persian),
			"Polish" => Some(Polish),
			"Portuguese" => Some(Portuguese),
			"Quechua" => Some(Quechua),
			"Romanian" | "Moldavian" | "Moldovan" => Some(Romanian),
			"Romansh" => Some(Romansh),
			"Rundi" | "Kirundi" => Some(Rundi),
			"Russian" => Some(Russian),
			"Samoan" => Some(Samoan),
			"Sango" => Some(Sango),
			"Sanskrit" | "Saṃskṛta" => Some(Sanskrit),
			"Sardinian" => Some(Sardinian),
			"Serbian" => Some(Serbian),
			"Shona" => Some(Shona),
			"Sichuan Yi" | "Nuosu" => Some(Sichuan_Yi),
			"Sindhi" => Some(Sindhi),
			"Sinhala" | "Sinhalese" => Some(Sinhala),
			"Slovak" => Some(Slovak),
			"Slovenian" | "Slovene" => Some(Slovenian),
			"Somali" => Some(Somali),
			"South Ndebele" | "Southern Ndebele" => Some(South_Ndebele),
			"Southern Sotho" => Some(Southern_Sotho),
			"Spanish" | "Castilian" => Some(Spanish),
			"Sundanese" => Some(Sundanese),
			"Swahili" => Some(Swahili),
			"Swati" | "Swazi" => Some(Swati),
			"Swedish" => Some(Swedish),
			"Tagalog" | "Filipino" | "Pilipino" => Some(Tagalog),
			"Tahitian" | "Reo Mā`ohi" => Some(Tahitian),
			"Tajik" => Some(Tajik),
			"Tamil" => Some(Tamil),
			"Tatar" => Some(Tatar),
			"Telugu" => Some(Telugu),
			"Thai" => Some(Thai),
			"Tibetan" | "Standard Tibetan" => Some(Tibetan),
			"Tigrinya" => Some(Tigrinya),
			"Tonga" => Some(Tonga),
			"Tsonga" => Some(Tsonga),
			"Tswana" => Some(Tswana),
			"Turkish" => Some(Turkish),
			"Turkmen" => Some(Turkmen),
			"Twi" => Some(Twi),
			"Uighur" | "Uyghur" => Some(Uighur),
			"Ukrainian" => Some(Ukrainian),
			"Urdu" => Some(Urdu),
			"Uzbek" => Some(Uzbek),
			"Venda" => Some(Venda),
			"Vietnamese" => Some(Vietnamese),
			"Volapük" | "Volapuk" => Some(Volapuk),
			"Walloon" => Some(Walloon),
			"Welsh" => Some(Welsh),
			"Western Frisian" | "Frisian" => Some(Western_Frisian),
			"Wolof" => Some(Wolof),
			"Xhosa" => Some(Xhosa),
			"Yiddish" => Some(Yiddish),
			"Yoruba" => Some(Yoruba),
			"Zhuang" | "Chuang" => Some(Zhuang),
			"Zulu" => Some(Zulu),
			_ => None,
		}
	}
	
	#[inline(always)]
	pub(crate) fn from_lower_case_iso_639_1_alpha_2_language_code(lower_case_iso_639_1_alpha_2_language_code: &str) -> Option<Self>
	{
		use self::Iso639Language::*;
		
		match lower_case_iso_639_1_alpha_2_language_code
		{
			"ab" => Some(Abkhazian),
			"aa" => Some(Afar),
			"af" => Some(Afrikaans),
			"ak" => Some(Akan),
			"sq" => Some(Albanian),
			"am" => Some(Amharic),
			"ar" => Some(Arabic),
			"an" => Some(Aragonese),
			"hy" => Some(Armenian),
			"as" => Some(Assamese),
			"av" => Some(Avaric),
			"ae" => Some(Avestan),
			"ay" => Some(Aymara),
			"az" => Some(Azerbaijani),
			"bm" => Some(Bambara),
			"ba" => Some(Bashkir),
			"eu" => Some(Basque),
			"be" => Some(Belarusian),
			"bn" => Some(Bengali),
			"bh" => Some(Bihari),
			"bi" => Some(Bislama),
			"bs" => Some(Bosnian),
			"br" => Some(Breton),
			"bg" => Some(Bulgarian),
			"my" => Some(Burmese),
			"ca" => Some(Catalan),
			"km" => Some(Central_Khmer),
			"ch" => Some(Chamorro),
			"ce" => Some(Chechen),
			"ny" => Some(Chichewa),
			"zh" => Some(Chinese),
			"cu" => Some(Church_Slavic),
			"cv" => Some(Chuvash),
			"kw" => Some(Cornish),
			"co" => Some(Corsican),
			"cr" => Some(Cree),
			"hr" => Some(Croatian),
			"cs" => Some(Czech),
			"da" => Some(Danish),
			"dv" => Some(Divehi),
			"nl" => Some(Dutch),
			"dz" => Some(Dzongkha),
			"en" => Some(English),
			"eo" => Some(Esperanto),
			"et" => Some(Estonian),
			"ee" => Some(Ewe),
			"fo" => Some(Faroese),
			"fj" => Some(Fijian),
			"fi" => Some(Finnish),
			"fr" => Some(French),
			"ff" => Some(Fulah),
			"gd" => Some(Gaelic),
			"gl" => Some(Galician),
			"lg" => Some(Ganda),
			"ka" => Some(Georgian),
			"de" => Some(German),
			"el" => Some(Greek),
			"gn" => Some(Guarani),
			"gu" => Some(Gujarati),
			"ht" => Some(Haitian),
			"ha" => Some(Hausa),
			"he" => Some(Hebrew),
			"hz" => Some(Herero),
			"hi" => Some(Hindi),
			"ho" => Some(Hiri_Motu),
			"hu" => Some(Hungarian),
			"is" => Some(Icelandic),
			"io" => Some(Ido),
			"ig" => Some(Igbo),
			"id" => Some(Indonesian),
			"ia" => Some(Interlingua),
			"ie" => Some(Interlingue),
			"iu" => Some(Inuktitut),
			"ik" => Some(Inupiaq),
			"ga" => Some(Irish),
			"it" => Some(Italian),
			"ja" => Some(Japanese),
			"jv" => Some(Javanese),
			"kl" => Some(Kalaallisut),
			"kn" => Some(Kannada),
			"kr" => Some(Kanuri),
			"ks" => Some(Kashmiri),
			"kk" => Some(Kazakh),
			"ki" => Some(Kikuyu),
			"rw" => Some(Kinyarwanda),
			"ky" => Some(Kirghiz),
			"kv" => Some(Komi),
			"kg" => Some(Kongo),
			"ko" => Some(Korean),
			"kj" => Some(Kuanyama),
			"ku" => Some(Kurdish),
			"lo" => Some(Lao),
			"la" => Some(Latin),
			"lv" => Some(Latvian),
			"li" => Some(Limburgan),
			"ln" => Some(Lingala),
			"lt" => Some(Lithuanian),
			"lu" => Some(Luba_Katanga),
			"lb" => Some(Luxembourgish),
			"mk" => Some(Macedonian),
			"mg" => Some(Malagasy),
			"ms" => Some(Malay),
			"ml" => Some(Malayalam),
			"mt" => Some(Maltese),
			"gv" => Some(Manx),
			"mi" => Some(Maori),
			"mr" => Some(Marathi),
			"mh" => Some(Marshallese),
			"mn" => Some(Mongolian),
			"na" => Some(Nauru),
			"nv" => Some(Navajo),
			"ng" => Some(Ndonga),
			"ne" => Some(Nepali),
			"nd" => Some(North_Ndebele),
			"se" => Some(Northern_Sami),
			"no" => Some(Norwegian),
			"nb" => Some(Norwegian_Bokmal),
			"nn" => Some(Norwegian_Nynorsk),
			"oc" => Some(Occitan),
			"oj" => Some(Ojibwa),
			"or" => Some(Oriya),
			"om" => Some(Oromo),
			"os" => Some(Ossetian),
			"pi" => Some(Pali),
			"pa" => Some(Panjabi),
			"ps" => Some(Pashto),
			"fa" => Some(Persian),
			"pl" => Some(Polish),
			"pt" => Some(Portuguese),
			"qu" => Some(Quechua),
			"ro" | "mo" => Some(Romanian), // mo is deprecated
			"rm" => Some(Romansh),
			"rn" => Some(Rundi),
			"ru" => Some(Russian),
			"sm" => Some(Samoan),
			"sg" => Some(Sango),
			"sa" => Some(Sanskrit),
			"sc" => Some(Sardinian),
			"sr" => Some(Serbian),
			"sn" => Some(Shona),
			"ii" => Some(Sichuan_Yi),
			"sd" => Some(Sindhi),
			"si" => Some(Sinhala),
			"sk" => Some(Slovak),
			"sl" => Some(Slovenian),
			"so" => Some(Somali),
			"nr" => Some(South_Ndebele),
			"st" => Some(Southern_Sotho),
			"es" => Some(Spanish),
			"su" => Some(Sundanese),
			"sw" => Some(Swahili),
			"ss" => Some(Swati),
			"sv" => Some(Swedish),
			"tl" => Some(Tagalog),
			"ty" => Some(Tahitian),
			"tg" => Some(Tajik),
			"ta" => Some(Tamil),
			"tt" => Some(Tatar),
			"te" => Some(Telugu),
			"th" => Some(Thai),
			"bo" => Some(Tibetan),
			"ti" => Some(Tigrinya),
			"to" => Some(Tonga),
			"ts" => Some(Tsonga),
			"tn" => Some(Tswana),
			"tr" => Some(Turkish),
			"tk" => Some(Turkmen),
			"tw" => Some(Twi),
			"ug" => Some(Uighur),
			"uk" => Some(Ukrainian),
			"ur" => Some(Urdu),
			"uz" => Some(Uzbek),
			"ve" => Some(Venda),
			"vi" => Some(Vietnamese),
			"vo" => Some(Volapuk),
			"wa" => Some(Walloon),
			"cy" => Some(Welsh),
			"fy" => Some(Western_Frisian),
			"wo" => Some(Wolof),
			"xh" => Some(Xhosa),
			"yi" => Some(Yiddish),
			"yo" => Some(Yoruba),
			"za" => Some(Zhuang),
			"zu" => Some(Zulu),
			_ => None,
		}
	}
	
	#[inline(always)]
	pub(crate) fn to_iso_639_1_alpha_2_language_code(&self) -> &'static str
	{
		use self::Iso639Language::*;
		
		match *self
		{
			Abkhazian => "ab",
			Afar => "aa",
			Afrikaans => "af",
			Akan => "ak",
			Albanian => "sq",
			Amharic => "am",
			Arabic => "ar",
			Aragonese => "an",
			Armenian => "hy",
			Assamese => "as",
			Avaric => "av",
			Avestan => "ae",
			Aymara => "ay",
			Azerbaijani => "az",
			Bambara => "bm",
			Bashkir => "ba",
			Basque => "eu",
			Belarusian => "be",
			Bengali => "bn",
			Bihari => "bh",
			Bislama => "bi",
			Bosnian => "bs",
			Breton => "br",
			Bulgarian => "bg",
			Burmese => "my",
			Catalan => "ca",
			Central_Khmer => "km",
			Chamorro => "ch",
			Chechen => "ce",
			Chichewa => "ny",
			Chinese => "zh",
			Church_Slavic => "cu",
			Chuvash => "cv",
			Cornish => "kw",
			Corsican => "co",
			Cree => "cr",
			Croatian => "hr",
			Czech => "cs",
			Danish => "da",
			Divehi => "dv",
			Dutch => "nl",
			Dzongkha => "dz",
			English => "en",
			Esperanto => "eo",
			Estonian => "et",
			Ewe => "ee",
			Faroese => "fo",
			Fijian => "fj",
			Finnish => "fi",
			French => "fr",
			Fulah => "ff",
			Gaelic => "gd",
			Galician => "gl",
			Ganda => "lg",
			Georgian => "ka",
			German => "de",
			Greek => "el",
			Guarani => "gn",
			Gujarati => "gu",
			Haitian => "ht",
			Hausa => "ha",
			Hebrew => "he",
			Herero => "hz",
			Hindi => "hi",
			Hiri_Motu => "ho",
			Hungarian => "hu",
			Icelandic => "is",
			Ido => "io",
			Igbo => "ig",
			Indonesian => "id",
			Interlingua => "ia",
			Interlingue => "ie",
			Inuktitut => "iu",
			Inupiaq => "ik",
			Irish => "ga",
			Italian => "it",
			Japanese => "ja",
			Javanese => "jv",
			Kalaallisut => "kl",
			Kannada => "kn",
			Kanuri => "kr",
			Kashmiri => "ks",
			Kazakh => "kk",
			Kikuyu => "ki",
			Kinyarwanda => "rw",
			Kirghiz => "ky",
			Komi => "kv",
			Kongo => "kg",
			Korean => "ko",
			Kuanyama => "kj",
			Kurdish => "ku",
			Lao => "lo",
			Latin => "la",
			Latvian => "lv",
			Limburgan => "li",
			Lingala => "ln",
			Lithuanian => "lt",
			Luba_Katanga => "lu",
			Luxembourgish => "lb",
			Macedonian => "mk",
			Malagasy => "mg",
			Malay => "ms",
			Malayalam => "ml",
			Maltese => "mt",
			Manx => "gv",
			Maori => "mi",
			Marathi => "mr",
			Marshallese => "mh",
			Mongolian => "mn",
			Nauru => "na",
			Navajo => "nv",
			Ndonga => "ng",
			Nepali => "ne",
			North_Ndebele => "nd",
			Northern_Sami => "se",
			Norwegian => "no",
			Norwegian_Bokmal => "nb",
			Norwegian_Nynorsk => "nn",
			Occitan => "oc",
			Ojibwa => "oj",
			Oriya => "or",
			Oromo => "om",
			Ossetian => "os",
			Pali => "pi",
			Panjabi => "pa",
			Pashto => "ps",
			Persian => "fa",
			Polish => "pl",
			Portuguese => "pt",
			Quechua => "qu",
			Romanian => "ro",
			Romansh => "rm",
			Rundi => "rn",
			Russian => "ru",
			Samoan => "sm",
			Sango => "sg",
			Sanskrit => "sa",
			Sardinian => "sc",
			Serbian => "sr",
			Shona => "sn",
			Sichuan_Yi => "ii",
			Sindhi => "sd",
			Sinhala => "si",
			Slovak => "sk",
			Slovenian => "sl",
			Somali => "so",
			South_Ndebele => "nr",
			Southern_Sotho => "st",
			Spanish => "es",
			Sundanese => "su",
			Swahili => "sw",
			Swati => "ss",
			Swedish => "sv",
			Tagalog => "tl",
			Tahitian => "ty",
			Tajik => "tg",
			Tamil => "ta",
			Tatar => "tt",
			Telugu => "te",
			Thai => "th",
			Tibetan => "bo",
			Tigrinya => "ti",
			Tonga => "to",
			Tsonga => "ts",
			Tswana => "tn",
			Turkish => "tr",
			Turkmen => "tk",
			Twi => "tw",
			Uighur => "ug",
			Ukrainian => "uk",
			Urdu => "ur",
			Uzbek => "uz",
			Venda => "ve",
			Vietnamese => "vi",
			Volapuk => "vo",
			Walloon => "wa",
			Welsh => "cy",
			Western_Frisian => "fy",
			Wolof => "wo",
			Xhosa => "xh",
			Yiddish => "yi",
			Yoruba => "yo",
			Zhuang => "za",
			Zulu => "zu",
		}
	}
	
	/// Where a language is known by more than one name, the first in the list at Wikipedia <https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes> is used.
	#[inline(always)]
	pub(crate) fn wikipedia_preferred_english_spelling(&self) -> &'static str
	{
		use self::Iso639Language::*;
		
		match *self
		{
			Abkhazian => "Abkhazian",
			Afar => "Afar",
			Afrikaans => "Afrikaans",
			Akan => "Akan",
			Albanian => "Albanian",
			Amharic => "Amharic",
			Arabic => "Arabic",
			Aragonese => "Aragonese",
			Armenian => "Armenian",
			Assamese => "Assamese",
			Avaric => "Avaric",
			Avestan => "Avestan",
			Aymara => "Aymara",
			Azerbaijani => "Azerbaijani",
			Bambara => "Bambara",
			Bashkir => "Bashkir",
			Basque => "Basque",
			Belarusian => "Belarusian",
			Bengali => "Bengali",
			Bihari => "Bihari",
			Bislama => "Bislama",
			Bosnian => "Bosnian",
			Breton => "Breton",
			Bulgarian => "Bulgarian",
			Burmese => "Burmese",
			Catalan => "Catalan",
			Central_Khmer => "Central Khmer",
			Chamorro => "Chamorro",
			Chechen => "Chechen",
			Chichewa => "Chichewa",
			Chinese => "Chinese",
			Church_Slavic => "Church Slavic",
			Chuvash => "Chuvash",
			Cornish => "Cornish",
			Corsican => "Corsican",
			Cree => "Cree",
			Croatian => "Croatian",
			Czech => "Czech",
			Danish => "Danish",
			Divehi => "Divehi",
			Dutch => "Dutch",
			Dzongkha => "Dzongkha",
			English => "English",
			Esperanto => "Esperanto",
			Estonian => "Estonian",
			Ewe => "Ewe",
			Faroese => "Faroese",
			Fijian => "Fijian",
			Finnish => "Finnish",
			French => "French",
			Fulah => "Fulah",
			Gaelic => "Gaelic",
			Galician => "Galician",
			Ganda => "Ganda",
			Georgian => "Georgian",
			German => "German",
			Greek => "Greek",
			Guarani => "Guaraní",
			Gujarati => "Gujarati",
			Haitian => "Haitian",
			Hausa => "Hausa",
			Hebrew => "Hebrew",
			Herero => "Herero",
			Hindi => "Hindi",
			Hiri_Motu => "Hiri Motu",
			Hungarian => "Hungarian",
			Icelandic => "Icelandic",
			Ido => "Ido",
			Igbo => "Igbo",
			Indonesian => "Indonesian",
			Interlingua => "Interlingua",
			Interlingue => "Interlingue",
			Inuktitut => "Inuktitut",
			Inupiaq => "Inupiaq",
			Irish => "Irish",
			Italian => "Italian",
			Japanese => "Japanese",
			Javanese => "Javanese",
			Kalaallisut => "Kalaallisut",
			Kannada => "Kannada",
			Kanuri => "Kanuri",
			Kashmiri => "Kashmiri",
			Kazakh => "Kazakh",
			Kikuyu => "Kikuyu",
			Kinyarwanda => "Kinyarwanda",
			Kirghiz => "Kirghiz",
			Komi => "Komi",
			Kongo => "Kongo",
			Korean => "Korean",
			Kuanyama => "Kuanyama",
			Kurdish => "Kurdish",
			Lao => "Lao",
			Latin => "Latin",
			Latvian => "Latvian",
			Limburgan => "Limburgan",
			Lingala => "Lingala",
			Lithuanian => "Lithuanian",
			Luba_Katanga => "Luba-Katanga",
			Luxembourgish => "Luxembourgish",
			Macedonian => "Macedonian",
			Malagasy => "Malagasy",
			Malay => "Malay",
			Malayalam => "Malayalam",
			Maltese => "Maltese",
			Manx => "Manx",
			Maori => "Maori",
			Marathi => "Marathi",
			Marshallese => "Marshallese",
			Mongolian => "Mongolian",
			Nauru => "Nauru",
			Navajo => "Navajo",
			Ndonga => "Ndonga",
			Nepali => "Nepali",
			North_Ndebele => "North Ndebele",
			Northern_Sami => "Northern Sami",
			Norwegian => "Norwegian",
			Norwegian_Bokmal => "Norwegian Bokmål",
			Norwegian_Nynorsk => "Norwegian Nynorsk",
			Occitan => "Occitan",
			Ojibwa => "Ojibwa",
			Oriya => "Oriya",
			Oromo => "Oromo",
			Ossetian => "Ossetian",
			Pali => "Pali",
			Panjabi => "Panjabi",
			Pashto => "Pashto",
			Persian => "Persian",
			Polish => "Polish",
			Portuguese => "Portuguese",
			Quechua => "Quechua",
			Romanian => "Romanian",
			Romansh => "Romansh",
			Rundi => "Rundi",
			Russian => "Russian",
			Samoan => "Samoan",
			Sango => "Sango",
			Sanskrit => "Sanskrit",
			Sardinian => "Sardinian",
			Serbian => "Serbian",
			Shona => "Shona",
			Sichuan_Yi => "Sichuan Yi",
			Sindhi => "Sindhi",
			Sinhala => "Sinhala",
			Slovak => "Slovak",
			Slovenian => "Slovenian",
			Somali => "Somali",
			South_Ndebele => "South Ndebele",
			Southern_Sotho => "Southern Sotho",
			Spanish => "Spanish",
			Sundanese => "Sundanese",
			Swahili => "Swahili",
			Swati => "Swati",
			Swedish => "Swedish",
			Tagalog => "Tagalog",
			Tahitian => "Tahitian",
			Tajik => "Tajik",
			Tamil => "Tamil",
			Tatar => "Tatar",
			Telugu => "Telugu",
			Thai => "Thai",
			Tibetan => "Tibetan",
			Tigrinya => "Tigrinya",
			Tonga => "Tonga",
			Tsonga => "Tsonga",
			Tswana => "Tswana",
			Turkish => "Turkish",
			Turkmen => "Turkmen",
			Twi => "Twi",
			Uighur => "Uighur",
			Ukrainian => "Ukrainian",
			Urdu => "Urdu",
			Uzbek => "Uzbek",
			Venda => "Venda",
			Vietnamese => "Vietnamese",
			Volapuk => "Volapük",
			Walloon => "Walloon",
			Welsh => "Welsh",
			Western_Frisian => "Western Frisian",
			Wolof => "Wolof",
			Xhosa => "Xhosa",
			Yiddish => "Yiddish",
			Yoruba => "Yoruba",
			Zhuang => "Zhuang",
			Zulu => "Zulu",
		}
	}
}
